environment:
  PYTHON: "C:\\Python27"

install:
  - cmd: java -version
  - "%PYTHON%/Scripts/pip.exe install --user codecov"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

test_script:
  - mvn test
after_test:
  - cmd: dir %PYTHON%/Scripts/
  - "%PYTHON%/Scripts/codecov.exe"

cache:
  - '%HOMEPATH%\.m2' 

build: off